services:
  - type: web
    name: netflix-clone
    env: node
    buildCommand: npm install && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: PORT
        value: 10000